package kata7

/*
If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.

A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

The different possibilities are:

Colour here:        G G        B G        R G        B R
Becomes colour:      G          R          B          G
With a bigger example:

R R G B R G B B

	R B R G B R B
	 G G B R G G
	  G R G B G
	   B B R R
	    B G R
	     R B
	      G

You will be given the first row of the triangle as a string and its your job to return the final colour which would appear 
in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

The input string will only contain the uppercase letters R, G, B and there will be at least one letter 
so you do not have to test for invalid input.
If you are only given one colour as the input, return that colour.
Adapted from the 2017 British Informatics Olympiad
*/
func Triangle(row string) rune {
	if len(row) == 1 {
		return rune(row[0])
	}

	result := make([]rune, len(row)-1)
	for i := range row[:len(row)-1] {
		if row[i] == row[i+1] {
			result[i] = rune(row[i])
		} else {
			switch row[i] {
			case 'R':
				if row[i+1] == 'B' {
					result[i] = 'G'
				} else {
					result[i] = 'B'
				}
			case 'B':
				if row[i+1] == 'R' {
					result[i] = 'G'
				} else {
					result[i] = 'R'
				}
			case 'G':
				if row[i+1] == 'R' {
					result[i] = 'B'
				} else {
					result[i] = 'R'
				}
			}
		}
	}

	return Triangle(string(result))
}

func Triangle2(row string) rune {
	result := ""

	if len(row) == 1 {
		return rune(row[0])
	}
	for len(row) > 1 {
		for i := 0; i < len(row)-1; i++ {
			if row[i] == row[i+1] {
				result += string(row[i])
			} else {
				for _, char := range "RGB" {
					if rune(row[i]) != char && rune(row[i+1]) != char {
						result += string(char)
					}
				}
			}
		}
    row = result
			result = ""
	}
	return rune(row[0])
}


func Triangle3(s string) rune {
	a := []rune(s)
	for b := make([]rune, 0, len(a)-1); len(a) != 1; b = b[:0] {
		for i := range a[1:] {
			b = append(b, rgb(a[i], a[i+1]))
		}
		a, b = b, a
	}
	return a[0]
}
func rgb(a, b rune) rune {
	switch {
	case a == b:		return a
	case a == 'B' && b == 'G' || b == 'B' && a == 'G':		return 'R'
	case a == 'R' && b == 'B' || b == 'R' && a == 'B':		return 'G'
	}
	return 'B'
}

func Triangle4(row string) rune {
	rs := []rune(row)
	for len(rs) > 1 {
		for i := 0; i < len(rs)-1; i++ {
			switch s := string(rs[i : i+2]); s {
			case "GB", "BG":
				rs[i] = 'R'
			case "RB", "BR":
				rs[i] = 'G'
			case "RG", "GR":
				rs[i] = 'B'
			}
		}
		rs = rs[:len(rs)-1]
	}
	return rs[0]
}

func Triangle5(row string) rune {
	var rgb = map[rune]map[rune]rune{}
	rgb['R'] = map[rune]rune{}
	rgb['R']['R'] = 'R'
	rgb['R']['G'] = 'B'
	rgb['R']['B'] = 'G'
	rgb['G'] = map[rune]rune{}
	rgb['G']['R'] = 'B'
	rgb['G']['G'] = 'G'
	rgb['G']['B'] = 'R'
	rgb['B'] = map[rune]rune{}
	rgb['B']['R'] = 'G'
	rgb['B']['G'] = 'R'
	rgb['B']['B'] = 'B'
	for len(row) != 1 {
	  var row2 = make([]rune, len(row)-1)
	  for i := 0; i < len(row)-1; i++ {
		row2[i] = rgb[rune(row[i])][rune(row[i+1])]
	  }
	  row = string(row2)
	}
	return rune(row[0])
  }

  func Triangle6(row string) rune {
	processRow := row
	var processedStr string
	
	merge := map[string]string{
	  "BR": "G",
	  "RB": "G",
	  "RG": "B",
	  "GR": "B",
	  "GB": "R",
	  "BG": "R",
	  "RR": "R",
	  "GG": "G",
	  "BB": "B",
	}
	
	for len(processRow) > 1 {
	  for i, value := range processRow[1:] {
		mergeStr := string(value) + string(processRow[i])
		processedStr += merge[mergeStr]
	  }
	  processRow = processedStr
	  processedStr = ""
	}
	
	return []rune(processRow)[0]
  }